{
 "title": "Co2 & Light",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Light",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"light\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"bathroom\" or r[\"location\"] == \"bedroom\" or r[\"location\"] == \"kitchen\" or r[\"location\"] == \"garage\" or r[\"location\"] == \"living_room\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Co2 & Light",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\" or r[\"_field\"] == \"light\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"bathroom\" or r[\"location\"] == \"bedroom\" or r[\"location\"] == \"kitchen\" or r[\"location\"] == \"garage\" or r[\"location\"] == \"living_room\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Co2",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"bathroom\" or r[\"location\"] == \"bedroom\" or r[\"location\"] == \"kitchen\" or r[\"location\"] == \"garage\" or r[\"location\"] == \"living_room\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "co2 & Light",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"iot_sensors\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"environment\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"co2\" or r[\"_field\"] == \"light\")\r\n  |> filter(fn: (r) => r[\"location\"] == \"bathroom\" or r[\"location\"] == \"bedroom\" or r[\"location\"] == \"kitchen\" or r[\"location\"] == \"garage\" or r[\"location\"] == \"living_room\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}